version: '3.8'
services:
  llm-app-examples:
    container_name: llm-app-examples-server
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        APP_VARIANT: ${APP_VARIANT}
    ports:
      - "8080:8080"
    env_file:
      - .env
    stdin_open: true
    tty: true

  llm-app-examples-streamlit:
    container_name: llm-app-examples-streamlit
    build:
      context: ./examples/ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PATHWAY_REST_CONNECTOR_HOST=llm-app-examples-server